name: preprocessing

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'preprocessing/**'
      - 'data_clustering_raw/**'
      - '.github/workflows/preprocess.yml'

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: preprocessing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib seaborn matplotlib

      - name: Run preprocessing
        run: |
          python automate_Sahrul-Firdaus.py --data-path ../data_clustering_raw/data_clustering.csv --output-dir data_clustering_preprocessing --target-col Target

      - name: Upload processed data
        uses: actions/upload-artifact@v4
        with:
          name: data_clustering_preprocessing
          path: preprocessing/data_clustering_preprocessing/
