global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "inference_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "custom_exporter"
    static_configs:
      - targets: ["localhost:9101"]
